Human Activity Recognisation Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
# IMport data
training = pd.read_csv('har_train.csv')
test = pd.read_csv('har_validate.csv')

In [4]:
training.shape

(13737, 53)

In [6]:
training.head()

,classe,roll_belt,pitch_belt,yaw_belt,total_accel_belt,gyros_belt_x,gyros_belt_y,gyros_belt_z,accel_belt_x,accel_belt_y,...,total_accel_forearm,gyros_forearm_x,gyros_forearm_y,gyros_forearm_z,accel_forearm_x,accel_forearm_y,accel_forearm_z,magnet_forearm_x,magnet_forearm_y,magnet_forearm_z
0,A,1.41,8.07,-94.4,3,0.00,0.0,-0.02,-21,4,...,36,0.03,0.00,-0.02,192,203,-215,-17,654,476
1,A,1.41,8.07,-94.4,3,0.02,0.0,-0.02,-22,4,...,36,0.02,0.00,-0.02,192,203,-216,-18,661,473
2,A,1.42,8.07,-94.4,3,0.00,0.0,-0.02,-20,5,...,36,0.03,-0.02,0.00,196,204,-213,-18,658,469
3,A,1.48,8.05,-94.4,3,0.02,0.0,-0.03,-22,3,...,36,0.02,-0.02,0.00,189,206,-214,-16,658,469
4,A,1.45,8.06,-94.4,3,0.02,0.0,-0.02,-21,4,...,36,0.02,-0.02,-0.03,193,203,-215,-9,660,478

In [7]:
# Based on these above values you have to predict the class

In [9]:
training['classe'].unique()

array(['A', 'B', 'C', 'D', 'E'], dtype=object)

In [12]:
#Split into x and y
x_train = training.drop('classe', axis =1)
y_train = training.loc[:,'classe']

x_test = test.drop('classe', axis =1)
y_test = test.loc[:,'classe']

In [13]:
x_train

,roll_belt,pitch_belt,yaw_belt,total_accel_belt,gyros_belt_x,gyros_belt_y,gyros_belt_z,accel_belt_x,accel_belt_y,accel_belt_z,...,total_accel_forearm,gyros_forearm_x,gyros_forearm_y,gyros_forearm_z,accel_forearm_x,accel_forearm_y,accel_forearm_z,magnet_forearm_x,magnet_forearm_y,magnet_forearm_z
0,1.41,8.07,-94.4,3,0.00,0.00,-0.02,-21,4,22,...,36,0.03,0.00,-0.02,192,203,-215,-17,654,476
1,1.41,8.07,-94.4,3,0.02,0.00,-0.02,-22,4,22,...,36,0.02,0.00,-0.02,192,203,-216,-18,661,473
2,1.42,8.07,-94.4,3,0.00,0.00,-0.02,-20,5,23,...,36,0.03,-0.02,0.00,196,204,-213,-18,658,469
3,1.48,8.05,-94.4,3,0.02,0.00,-0.03,-22,3,21,...,36,0.02,-0.02,0.00,189,206,-214,-16,658,469
4,1.45,8.06,-94.4,3,0.02,0.00,-0.02,-21,4,21,...,36,0.02,-0.02,-0.03,193,203,-215,-9,660,478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13732,154.00,-32.70,125.0,24,0.29,0.05,-0.36,67,51,-218,...,32,1.36,-2.83,-0.61,-227,221,0,-592,-85,431
13733,154.00,-32.90,126.0,24,0.31,0.05,-0.41,69,52,-217,...,31,1.33,-2.89,-0.71,-230,200,-8,-571,-126,404
13734,145.00,-35.50,130.0,19,0.37,0.00,-0.64,47,13,-177,...,29,1.54,-1.20,0.05,-263,-99,-45,-116,-654,-70
13735,143.00,-35.90,131.0,18,0.37,-0.02,-0.59,46,18,-172,...,32,1.48,-0.90,0.05,-270,-141,-51,-68,-678,-98
13736,143.00,-36.00,132.0,18,0.35,-0.02,-0.57,42,25,-171,...,33,1.38,-0.64,0.08,-278,-159,-52,-60,-686,-110

In [14]:
# DO the Modelling

model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [16]:
train_pred = model.predict(x_train)

In [17]:
pred = model.predict(x_test)

In [18]:
pred

array(['A', 'A', 'A', ..., 'E', 'E', 'E'], dtype='<U1')

In [19]:
from sklearn import metrics

print(metrics.confusion_matrix(pred,y_test, labels=["A","B","C","D","E"]))

[[1070  127  223  102   51]
 [  95  685  106   35  239]
 [ 262  145  512  271   95]
 [ 212   76  136  441  143]
 [  35  106   49  115  554]]

In [20]:
print(metrics.classification_report(pred,y_test, labels=["A","B","C","D","E"]))

              precision    recall  f1-score   support

           A       0.64      0.68      0.66      1573
           B       0.60      0.59      0.60      1160
           C       0.50      0.40      0.44      1285
           D       0.46      0.44      0.45      1008
           E       0.51      0.64      0.57       859

    accuracy                           0.55      5885
   macro avg       0.54      0.55      0.54      5885
weighted avg       0.55      0.55      0.55      5885

In [21]:
# Hyperparameter tuning
"""
var_smoothing

_IncompleteInputError: incomplete input (1883770805.py, line 2)